---
title: "Report for stocks"
output: 
  flexdashboard::flex_dashboard:
    theme: simplex
    orientation: rows
    vertical_layout: scroll
    social: menu
    runtime: shiny
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}

library(flexdashboard)
library(quantmod)
library(dplyr)
library(tidyr)
library(PerformanceAnalytics)
library(ggplot2)
library(highcharter)
library(viridisLite)
library(forecast)
require(treemap)
library(flexdashboard)
library(shiny)
library(plotly)
library(ggthemes)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )


symbolList <- read.csv("~/Finances/cod_acoes.txt", sep="")  
symbolList <- as.data.frame(symbolList)

symbolList <- as.vector(t(extract(symbolList, col= Codigo, "[[A-Z]+[0-9]]")))

database <- reactive({
  stock <- getSymbols(Symbols = paste0("BVMF:",input$Ativo),
                    src = 'google', 
                    auto.assign = FALSE)
  
  colnames(stock) <- c("open","high","low","close","volume")
  
  stock <- stock %>% as.data.frame() %>% mutate(date = index(stock)) %>%   drop_na() %>% mutate(valuation = ave(.$close, FUN = function(y) c(0, diff(y))), daily.return = as.vector(dailyReturn(stock)))
  
return(stock)
})

# Function to calculate daily, weekly and monthly minimum
min.n <- function(d, n = input$Qtd)
{
   minimos <- NULL
    minimos[[1]] <- d %>% filter(Daily %in% head(sort(d$Daily), n= n)) %>% select(Stock, Daily) 
    minimos[[2]] <- d %>% filter(Weekly %in% head(sort(d$Weekly), n= n)) %>% select(Stock, Weekly) 
    minimos[[3]] <- d %>% filter(Monthly %in% head(sort(d$Monthly), n= n)) %>% select(Stock, Monthly)
  return(minimos)
}

# Function to calculate daily, weekly and monthly maximum
max.n <- function(d, n = input$Qtd)
{
   maximos <- NULL
    maximos[[1]] <- d %>% filter(Daily %in% tail(sort(d$Daily), n= n)) %>% select(Stock, Daily)
    maximos[[2]] <- d %>% filter(Weekly %in% tail(sort(d$Weekly), n= n)) %>% select(Stock, Weekly)
    maximos[[3]] <- d %>% filter(Monthly %in% tail(sort(d$Monthly), n= n)) %>% select(Stock, Monthly)
  return(maximos)
}

```

Sidebar {.sidebar}
=======================================================================

```{r Sidebar}

# Define inputs

selectInput(inputId = 'Ativo', choices = symbolList, label = 'Select the stock to analyze')

sliderInput('Qtd', label = 'Amount of Assets', min = 1, max = 10, value = 3, step = 1)


```

The maximum and minimum values are defined based on closing prices

Detail Version
=======================================================================

Row
-----------------------------------------------------------------------


### Last Closed {.value-box}

```{r Atual Value}

# Emit the download rate
renderValueBox({
  atual.value <- database() %>% filter(close==last(close)) %>% .$close
  valueBox(
    value = atual.value,
    icon = "ion-stats-bars"
  )
})
```

### Historical Minimum {.value-box}

```{r Historical Min}

# Emit the download rate
renderValueBox({
  historical.min <- database() %>% filter(close==min(close))
  valueBox(
    value = historical.min$close,
    icon = "ion-arrow-graph-down-right",
     
  )
})
```

### Historical Maximun {.value-box}

```{r Historical Max}

renderValueBox({
  historical.max <- database() %>% filter(close==max(close))
  valueBox(
    value = historical.max$close,
    icon = "ion-arrow-graph-up-right",
    color = if (last(database()$close) >= historical.max$close) "warning" else "primary"
  )
})
```


Row {data-height=500}
-----------------------------------------------------------------------

### Graphic

```{r Render Graphics}

 renderHighchart({
   
   x <- getSymbols(Symbols = paste0("BVMF:",input$Ativo),
                   src = 'google', 
                   auto.assign = FALSE)
   
   hchart(x) %>% hc_add_theme(thm)
 })

#highchartOutput(highchartOutput)

```

Row {data-width=800}
-----------------------------------------------------------------------

### Summary Table

```{r Render Table}

renderTable({
  tab <-
  database() %>% mutate(Year = format(date, '%Y'), up =  c(((.$close[2:length(.$close)] -
  .$close[1:length(.$close) - 1]) > 0
  ), "NA")) %>% group_by(Year) %>%
  summarise(
  Open = first(open),
  Close = last(close),
  Min. = round(min(close, na.rm = TRUE), 2),
  Max. = max(close, na.rm = TRUE),
  Ups = sum(up == 'TRUE'),
  Downs = sum(up == 'FALSE')
  ) %>% ungroup()
  })

```

Generally Version {data-orientation=columns}
=======================================================================

```{r, warning=FALSE}

# Function to calculate daily, weekly and monthly returns
valuation <- function(ii)
{
    rtn <- as.data.frame(NULL)
    stk <- getSymbols(Symbols = paste0("BVMF:",ii), src = 'google', auto.assign = FALSE, warnings = FALSE)
    rtn.1 <- (last(dailyReturn(stk))*100) %>% round(.,2)
    rtn.2 <- (last(weeklyReturn(stk))*100) %>% round(.,2)
    rtn.3 <- (last(monthlyReturn(stk))*100) %>% round(.,2)
    last.date <- index(tail(dailyReturn(stk), n = 1))
    rtn <- cbind.data.frame(ii, rtn.1, rtn.2, rtn.3, last.date) %>% 
      rename(Stock = ii, Daily = rtn.1, Weekly = rtn.2, Monthly = rtn.3)
    
}

# Calculate returns to all the stocks in Ibovespa 
t <- NULL

for(i in symbolList)
{
  t <- rbind(t, valuation(i))
}

```


Column {.tabset data-width=500}
-----------------------------------------------------------------------

### Daily

```{r}

  renderHighchart({
  
x <- min.n(t,n = input$Qtd)
y <- x[[1]] %>% as.data.frame() %>% arrange(Daily)
    chart <- highchart() %>%
      hc_chart(type = 'column') %>%
      hc_legend(enabled = FALSE) %>%
      hc_xAxis(categories = as.vector(y[,1]),
               title = list(text = 'Stocks')) %>%
      hc_yAxis(title = list(text = 'Daily Returns(%)')) %>%
      hc_plotOptions(series = list(dataLabels = list(enabled = TRUE))) %>%
      hc_add_series(name = 'Population, 2010', data =as.vector(y[,2])) %>% hc_add_theme(hc_theme_smpl()) %>%
       hc_colors(c('#d01010', '#d01010')) %>%
       hc_tooltip(enabled = FALSE)
    
    chart

  })


```


### Weekly

```{r}

  renderHighchart({
x <- min.n(t,n = input$Qtd)
y <- x[[2]] %>% as.data.frame() %>% arrange(Weekly)
    chart2 <- highchart() %>%
      hc_chart(type = 'column') %>%
      hc_legend(enabled = FALSE) %>%
      hc_xAxis(categories = as.vector(y[,1]),
               title = list(text = 'Stocks')) %>%
      hc_yAxis(title = list(text = 'Daily Returns(%)')) %>%
      hc_plotOptions(series = list(dataLabels = list(enabled = TRUE))) %>%
      hc_add_series(name = 'Population, 2010', data =as.vector(y[,2])) %>% hc_add_theme(hc_theme_smpl()) %>%
       hc_colors(c('#d01010', '#d01010')) %>%
       hc_tooltip(enabled = FALSE)

    chart2

  })

highchartOutput('barplot')

```


### Monthly

```{r}

  renderHighchart({
    x <- min.n(t,n = input$Qtd)
    y <- x[[3]] %>% as.data.frame() %>% arrange(Monthly)
    chart3 <- highchart() %>%
      hc_chart(type = 'column') %>%
      hc_legend(enabled = FALSE) %>%
      hc_xAxis(categories = as.vector(y[,1]),
               title = list(text = 'Stocks')) %>%
      hc_yAxis(title = list(text = 'Daily Returns(%)')) %>%
      hc_plotOptions(series = list(dataLabels = list(enabled = TRUE))) %>%
      hc_add_series(name = 'Population, 2010', data =as.vector(y[,2])) %>% hc_add_theme(hc_theme_smpl()) %>%
       hc_colors(c('#d01010', '#d01010')) %>%
       hc_tooltip(enabled = FALSE)

    chart3

  })

```

Column {.tabset data-width=500}
-----------------------------------------------------------------------

### Daily

```{r}

renderHighchart({
x <- max.n(t,n = input$Qtd)
y <- x[[1]] %>% as.data.frame() %>% arrange(Daily)
    chart.1 <- highchart() %>%
      hc_chart(type = 'column') %>%
      hc_legend(enabled = FALSE) %>%
      hc_xAxis(categories = as.vector(y[,1]),
               title = list(text = 'Stocks')) %>%
      hc_yAxis(title = list(text = 'Daily Returns(%)')) %>%
      hc_plotOptions(series = list(dataLabels = list(enabled = TRUE))) %>%
      hc_add_series(name = 'Population, 2010', data =as.vector(y[,2])) %>% hc_add_theme(hc_theme_smpl()) %>%
       hc_colors(c('#1079d0', '#1079d0')) %>%
       hc_tooltip(enabled = FALSE)

    chart.1

  })

```


### Weekly

```{r}

renderHighchart({
x <- max.n(t,n = input$Qtd)
y <- x[[2]] %>% as.data.frame() %>% arrange(Weekly)
    chart.2 <- highchart() %>%
      hc_chart(type = 'column') %>%
      hc_legend(enabled = FALSE) %>%
      hc_xAxis(categories = as.vector(y[,1]),
               title = list(text = 'Stocks')) %>%
      hc_yAxis(title = list(text = 'Daily Returns(%)')) %>%
      hc_plotOptions(series = list(dataLabels = list(enabled = TRUE))) %>%
      hc_add_series(name = 'Population, 2010', data =as.vector(y[,2])) %>% hc_add_theme(hc_theme_smpl()) %>%
       hc_colors(c('#1079d0', '#1079d0')) %>%
       hc_tooltip(enabled = FALSE)

    chart.2

  })

```


### Monthly

```{r}

renderHighchart({
x <- max.n(t,n = input$Qtd)
y <- x[[3]] %>% as.data.frame() %>% arrange(Monthly)
    chart.3 <- highchart() %>%
      hc_chart(type = 'column') %>%
      hc_legend(enabled = FALSE) %>%
      hc_xAxis(categories = as.vector(y[,1]),
               title = list(text = 'Stocks')) %>%
      hc_yAxis(title = list(text = 'Daily Returns(%)')) %>%
      hc_plotOptions(series = list(dataLabels = list(enabled = TRUE))) %>%
      hc_add_series(name = 'Population, 2010', data =as.vector(y[,2])) %>% hc_add_theme(hc_theme_smpl()) %>%
       hc_colors(c('#1079d0', '#1079d0')) %>%
       hc_tooltip(enabled = FALSE)

    chart.3

  })

```